#!/bin/sh

# Intended to be called as lxc network hook using lxc.network.script.up with
# lxc.hook.version=1 to pass arguments through the environment.
IFNAME=$LXC_NET_PEER

# Enable hairpin mode for this interface. This allows packets coming
# into a bridge through this interface to be routed back out of the same
# port, which is normally not allowed. This is needed for vuurmuur
# bounce rules to work (e.g. the web container connecting to port 80 on
# the external IP, which should be routed back to itself).
bridge link set dev "$IFNAME" hairpin on
