[Service]
# These cause startup to fail in an unprivileged container
# https://github.com/systemd/systemd/issues/34565#issuecomment-4418491056
LockPersonality=false
PrivateDevices=false
ProtectClock=false
ProtectHostname=false
ProtectKernelLogs=false
ProtectKernelModules=false
ProtectKernelTunables=false
RestrictRealtime=false
